# -*- coding: utf-8 -*-
"""1BM24CS305_week2_DFS_IDS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l9LjeJbREXj97hcJi4oYvXIcacwgO94Y
"""

from collections import deque

def print_grid(s):
    for i in range(0, 9, 3):
        print(*s[i:i+3])
    print()

def dfs(start, goal):
    q = deque([(start, [])])
    visited = {start}

    while q:
        state, path = q.popleft()

        if state == goal:

          for s in path + [state]:

            print_grid(s)
          print("goal reached")
          return

        zero = state.index(0)

        for m in [-3, 3, -1, 1]:
            p = zero + m
            if 0 <= p < 9:
                if m in (-1, 1) and zero // 3 != p // 3:
                    continue

                new = list(state)
                new[zero], new[p] = new[p], new[zero]
                new = tuple(new)

                if new not in visited:
                    visited.add(new)
                    q.append((new, path + [state]))

start = (1, 2, 3, 0, 4, 6, 7, 5, 8)
goal = (1, 2, 3, 4, 5, 6, 7, 8, 0)

dfs(start, goal)

def print_as_grid(state):
    """Prints the 1D state array as a 3x3 grid."""
    for i in range(0, 9, 3):
        print(state[i:i+3])
    print()

def dfs_limited(state, goal, limit, current_depth, visited, path):

    if state == goal:
        print("Goal Found!")
        print("Path taken:")
        for step, s in enumerate(path):
            print(f"Step {step}:")
            print_as_grid(s)
        print("Goal State:")
        print_as_grid(state)
        return True


    if current_depth >= limit:
        return False


    visited.add(tuple(state))


    zero_index = state.index(0)
    zero_row = zero_index // 3


    for move in [-3, 3, -1, 1]:

        new_pos = zero_index + move


        if 0 <= new_pos <= 8:

            new_row = new_pos // 3
            if (move == -3 or move == 3) or (zero_row == new_row):
                new_state = list(state)
                new_state[zero_index], new_state[new_pos] = new_state[new_pos], new_state[zero_index]

                if tuple(new_state) not in visited:
                    path.append(new_state)
                    if dfs_limited(new_state, goal, limit, current_depth + 1, visited, path) == True:
                        return True
                    path.pop()


    visited.remove(tuple(state))

    return False

def iterative_deepening_search(initial_state, goal):

    for depth_limit in range(31):

        visited = set()
        path = [initial_state]
        print(f"Searching with depth limit: {depth_limit}")

        if dfs_limited(initial_state, goal, depth_limit, 0, visited, path) == True:
            return True
    return False


if __name__ == "__main__":
    start_state = [1, 2, 3, 4, 0, 5, 7, 8, 6]
    goal_state = [1, 2, 3, 4, 5, 6, 7, 8, 0]

    print("Starting Iterative Deepening Search with path tracking...")
    success = iterative_deepening_search(start_state, goal_state)
    if not success:
        print("Goal not found within the depth limit of 30.")